import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>My Next.js App</title>
                <meta name="description" content="Generated by create-next-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 className="text-4xl font-bold">Welcome to My Next.js App</h1>
                <Link href="/products">
                    <a className="text-blue-500">Go to Products</a>
                </Link>
            </main>
        </div>
    );
};

export default Home;
